title:        '@hussfelt'
tagline:      'Home of @hussfelt'
description:  'Autodidact technical creative geek, with a passion for doing the right thing. Technical advisor.'
url:          http://hussfelt.net
version:      1.1.2
author:
  name:       'Henrik'
  email:      'henrik@henrik.se'
markdown:     rdiscount
permalink:    pretty
pygments:  true
paginate:     1
